data:
  class_path: modules.datamodule.PUFMNISTDataModule
  init_args:
    pn_wrap_kwargs:
      positive_labels: [0, 2, 3, 4, 6]
    pu_wrap_kwargs:
      positive_count: 1_000
      unlabeled_count: 60_000
    train_dataloader_kwargs:
      batch_size: 30_000
    val_dataloader_kwargs:
      batch_size: 10_000
model:
  class_path: modules.system.nnPUSystem
  init_args:
    model: modules.model.KiryoMLP
    cost_function: modules.loss.LogisticCostFunction
    mixup_loss: modules.mixup.ChenMixupLoss
    mixup_alpha: 0.3
optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 1e-4
    weight_decay: 5e-3
trainer:
  logger:
    init_args:
      repo: results/mixup/
      experiment: mixup
  max_epochs: 200
